# Generated by Django 3.0.6 on 2020-08-19 22:01

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_gamepost_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepost',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=19),
        ),
    ]
