# Generated by Django 3.0.6 on 2020-08-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200819_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamepost',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='gamepost',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
