# Generated by Django 3.0.6 on 2020-09-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200821_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepost',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
