# Generated by Django 3.0.6 on 2020-10-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_gamepost_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepost',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
