# Generated by Django 3.0.6 on 2020-10-29 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201028_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamepost',
            old_name='avaliable',
            new_name='available',
        ),
    ]
