# Generated by Django 3.0.6 on 2020-11-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201028_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameidentifier',
            name='game_choice',
            field=models.CharField(choices=[('default', 'NO CATEGORY'), ('MOBA', 'MOBA'), ('FPS', 'FPS'), ('MMORPG', 'MMORPG'), ('Adventure', 'Adventure'), ('TPS', 'TPS'), ('MMO', 'MMO'), ('2D', '2D'), ('KRAL', 'KRAL')], default='default', max_length=72),
        ),
    ]
