# Generated by Django 3.0.6 on 2020-11-20 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201117_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamepost',
            name='available',
        ),
    ]
