# Generated by Django 3.0.6 on 2020-08-20 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200819_1801'),
        ('user', '0002_profile_reviewscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=48)),
                ('review_type', models.CharField(choices=[('Negative', 'Negative'), ('Positive', 'Positive')], max_length=72)),
                ('review_slug', models.SlugField(max_length=48, unique=True)),
                ('review_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('review_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.gamePost')),
            ],
        ),
    ]
