# Generated by Django 3.0.6 on 2020-08-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200820_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='review_text',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
