# Generated by Django 3.0.6 on 2020-08-22 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_reviews_review_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromReview', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toReview', to=settings.AUTH_USER_MODEL),
        ),
    ]
